import type { Metadata } from "next";
// Asegúrate de instalar el paquete 'geist': npm install geist
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.className} ${GeistMono.className}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
